#!/bin/bash

read -p "Enter any 5-digit number: " n

if ! [[ "$n" =~ ^[0-9]{5}$ ]]; then
    echo "Please enter a valid 5-digit number."
    exit 1
fi
sum=0

while [ "$n" -gt 0 ]; do

    sum=$((sum + n % 10))

    n=$((n / 10)) 
done

echo "Sum of the digits = $sum"