#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <filename or full path>"
    exit 1
fi
file="$1"

if [ ! -e "$file" ]; then
    echo "Error: File '$file' does not exist."
    exit 1
fi
file_info=$(ls -l "$file")

echo "File Information:"
echo "$file_info"